apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  # version is required in Dapr 1.2.0
  version: v1
  type: state.redis
  metadata:
    - name: redisHost
      value: redis-master:6379
    - name: redisPassword
      value: ""
    - name: actorStateStore
      value: "true"
